-- Denver Data-Center / AI-Infrastructure 75-Companies import (applied to KOHLER OS)
-- Source: e93482e5-denver_data_center_75_companies_simplified.xlsx
-- Scope: 75 companies tagged niche='Data Center Buildout' with addresses, careers URLs,
--   and 'what they do' descriptions. Plus the 90 named contacts from the prior workbook.
-- Target DB: KOHLER OS (acwgirrldntjpzrhqmdh), which is what the deployed sandbox app reads.
-- Idempotent: NOT EXISTS / tag guards make this safe to re-run.

-- ===== 1. INSERT 41 new companies (niche='Data Center Buildout') =====
INSERT INTO companies (companyname, niche, mailing_address1, mailing_city, mailing_state, mailing_zip, company_about, careers_url, notes)
SELECT v.companyname, 'Data Center Buildout', v.address, v.city, v.state, v.zip, v.about, v.careers, v.note FROM (VALUES
  ('Alvine Engineering', '116 Inverness Dr E, Suite 206', 'Englewood', 'CO', '80112', 'Mechanical engineering, HVAC, controls, plumbing, piping, fire protection, field observation.', 'https://www.alvine.com/careers/', '[75-Companies enrichment] Address: 116 Inverness Dr E, Suite 206, Englewood, CO 80112 | Drive from 80226: 35–45 min | Employees: 51–200 | Category: MEP / fire / technology engineering consultant'),
  ('KL&A Engineers and Builders', '1717 Washington Ave, Golden, CO 80401; Lakewood office: 205 S Garrison St', 'Lakewood', 'CO', '80226', 'Structural/civil engineering, construction engineering, steel detailing, virtual design/construction.', 'https://www.klaa.com/careers', '[75-Companies enrichment] Address: 1717 Washington Ave, Golden, CO 80401; Lakewood office: 205 S Garrison St, Lakewood, CO 80226 | Drive from 80226: 5–25 min | Employees: ~140 | Category: Structural / construction engineering / design-build'),
  ('Mortenson', '3083 Walnut St, Suite 300', 'Denver', 'CO', '80205', 'GC, design-phase management, MEP coordination, preconstruction, construction execution.', 'https://www.mortenson.com/careers', '[75-Companies enrichment] Address: 3083 Walnut St, Suite 300, Denver, CO 80205 | Drive from 80226: 20–30 min | Employees: 5,000+ | Category: General contractor / data-center builder'),
  ('JE Dunn Construction', '2000 S Colorado Blvd, Suite 1000', 'Denver', 'CO', '80222', 'GC, project engineering, self-perform coordination, MEP coordination, commissioning coordination.', 'https://jedunn.com/careers/', '[75-Companies enrichment] Address: 2000 S Colorado Blvd, Suite 1000, Denver, CO 80222 | Drive from 80226: 25–35 min | Employees: 4,000+ | Category: General contractor / mission-critical builder'),
  ('Whiting-Turner', '7800 E Union Ave, Suite 100', 'Denver', 'CO', '80237', 'GC, MEP coordination, BIM, construction sequencing, project controls.', 'https://www.whiting-turner.com/careers/', '[75-Companies enrichment] Address: 7800 E Union Ave, Suite 100, Denver, CO 80237 | Drive from 80226: 30–40 min | Employees: 4,000+ | Category: General contractor / mission-critical builder'),
  ('CoreSite', 'DE1: 910 15th St, Denver, CO 80202; DE2: 639 E 18th Ave, Denver, CO 80203; DE3: 4900 Race St', 'Denver', 'CO', '80216', 'Owner/operator development, facility operations, cooling/power systems, tenant fit-out, construction coordination.', 'https://www.coresite.com/careers', '[75-Companies enrichment] Address: DE1: 910 15th St, Denver, CO 80202; DE2: 639 E 18th Ave, Denver, CO 80203; DE3: 4900 Race St, Denver, CO 80216 | Drive from 80226: 20–35 min | Employees: 501–1,000 | Category: Data-center owner / operator / developer'),
  ('Tract', '3200 Cherry Creek S Dr, Suite 700', 'Denver', 'CO', '80209', 'Land acquisition, campus planning, powered infrastructure, development management.', 'https://tract.com/careers/', '[75-Companies enrichment] Address: 3200 Cherry Creek S Dr, Suite 700, Denver, CO 80209 | Drive from 80226: 25–35 min | Employees: 51–200 | Category: Data-center land / campus developer'),
  ('Rowan Digital Infrastructure', '1400 16th St, Suite 330', 'Denver', 'CO', '80202', 'Campus development, energy infrastructure, powered shells, design/construction coordination.', 'https://rowan.digital/careers/', '[75-Companies enrichment] Address: 1400 16th St, Suite 330, Denver, CO 80202 | Drive from 80226: 20–25 min | Employees: 51–200 | Category: Data-center developer / sustainable infrastructure'),
  ('Prime Data Centers', '3660 Blake St, Suite 600, Denver, CO 80205; corporate HQ: 400 N Ervay St', 'Dallas', 'TX', '75313', 'Owner-side design management, controls, commissioning, operations.', 'https://primedatacenters.com/careers/', '[75-Companies enrichment] Address: 3660 Blake St, Suite 600, Denver, CO 80205; corporate HQ: 400 N Ervay St, Dallas, TX 75313 | Drive from 80226: 20–30 min | Employees: 201–500 | Category: Data-center owner / operator / developer'),
  ('DataBank', 'DEN1: 393 Inverness Pkwy, Englewood, CO 80112; DEN3: 1500 Champa St, Denver, CO 80202; DEN5: 6961 S Quentin St', 'Centennial', 'CO', '80112', 'Data-center operations, facilities engineering, expansions, tenant fit-outs.', 'https://www.databank.com/careers/', '[75-Companies enrichment] Address: DEN1: 393 Inverness Pkwy, Englewood, CO 80112; DEN3: 1500 Champa St, Denver, CO 80202; DEN5: 6961 S Quentin St, Centennial, CO 80112 | Drive from 80226: 20–40 min | Employees: 501–1,000 | Category: Data-center owner / operator'),
  ('H5 Data Centers', '5350 S Valentia Way', 'Greenwood Village', 'CO', '80111', 'Operations, colocation infrastructure, critical facilities, power/cooling maintenance and upgrades.', 'https://h5datacenters.com/careers/', '[75-Companies enrichment] Address: 5350 S Valentia Way, Greenwood Village, CO 80111 | Drive from 80226: 35–45 min | Employees: 51–200 | Category: Data-center owner / operator'),
  ('Iron Mountain Data Centers', '4300 Brighton Blvd', 'Denver', 'CO', '80216', 'Data-center operations, facility systems, power/cooling infrastructure, tenant support.', 'https://www.ironmountain.com/about-us/careers', '[75-Companies enrichment] Address: 4300 Brighton Blvd, Denver, CO 80216 | Drive from 80226: 25–35 min | Employees: 25,000+ global | Category: Data-center owner / operator'),
  ('Expedient', '7347 S Revere Pkwy', 'Centennial', 'CO', '80112', 'Operations, facilities, colocation, network/cloud infrastructure.', 'https://expedient.com/careers/', '[75-Companies enrichment] Address: 7347 S Revere Pkwy, Centennial, CO 80112 | Drive from 80226: 35–45 min | Employees: 501–1,000 | Category: Data-center owner / operator / colocation'),
  ('RadiusDC', '1500 Champa St', 'Denver', 'CO', '80202', 'Operations, interconnection, facility systems, tenant services.', 'https://www.radius-dc.com/careers', '[75-Companies enrichment] Address: 1500 Champa St, Denver, CO 80202 | Drive from 80226: 20–25 min | Employees: 11–50 | Category: Data-center owner / operator')
) AS v(companyname, address, city, state, zip, about, careers, note)
WHERE NOT EXISTS (SELECT 1 FROM companies c WHERE c.companyname = v.companyname);
INSERT INTO companies (companyname, niche, mailing_address1, mailing_city, mailing_state, mailing_zip, company_about, careers_url, notes)
SELECT v.companyname, 'Data Center Buildout', v.address, v.city, v.state, v.zip, v.about, v.careers, v.note FROM (VALUES
  ('QTS Data Centers', '1160 N Gun Club Rd', 'Aurora', 'CO', '80018', 'Owner/operator campus development, facility engineering, construction coordination.', 'https://qtsdatacenters.com/careers/', '[75-Companies enrichment] Address: 1160 N Gun Club Rd, Aurora, CO 80018 | Drive from 80226: 45–60 min | Employees: 1,001–5,000 | Category: Data-center owner / operator / developer'),
  ('EdgeConneX', 'DEN01/DEN02: 8535 / 8451 Highfield Pkwy', 'Englewood', 'CO', '80112', 'Operations, edge/colocation data centers, facility systems.', 'https://www.edgeconnex.com/company/careers/', '[75-Companies enrichment] Address: DEN01/DEN02: 8535 / 8451 Highfield Pkwy, Englewood, CO 80112 | Drive from 80226: 35–45 min | Employees: 201–500 | Category: Data-center owner / operator'),
  ('Google Data Centers / Google Cloud', 'Google Boulder: 2930 Pearl St / 3333 Walnut St, Boulder, CO 80301; Denver-region roles vary', NULL, NULL, NULL, 'Hyperscale mechanical systems, design standards, operations, commissioning.', 'https://www.google.com/about/careers/', '[75-Companies enrichment] Address: Google Boulder: 2930 Pearl St / 3333 Walnut St, Boulder, CO 80301; Denver-region roles vary | Drive from 80226: 45–60 min | Employees: 180,000+ global | Category: Cloud / hyperscale operator'),
  ('Comcast Critical Infrastructure / Data Centers', '4100 E Dry Creek Rd, Centennial, CO 80122; Centennial data-center site: 6900 S Peoria St, Centennial, CO', NULL, NULL, NULL, 'Telecom/data-center operations, facilities, HVAC, power systems.', 'https://jobs.comcast.com/', '[75-Companies enrichment] Address: 4100 E Dry Creek Rd, Centennial, CO 80122; Centennial data-center site: 6900 S Peoria St, Centennial, CO | Drive from 80226: 35–45 min | Employees: 100,000+ global | Category: Telecom / data-center operator'),
  ('Lakewood Electric Company', '3533 Timber Mill Pkwy, Suite A', 'Castle Rock', 'CO', '80109', 'Electrical/data-center special systems, testing, closeout, infrastructure upgrades.', 'https://www.lakewoodelectriccompany.com/careers', '[75-Companies enrichment] Address: 3533 Timber Mill Pkwy, Suite A, Castle Rock, CO 80109 | Drive from 80226: 40–55 min | Employees: 51–200 | Category: Electrical contractor / special systems'),
  ('Encore Electric', '7125 W Jefferson Ave, Suite 400', 'Lakewood', 'CO', '80235', 'Electrical construction, power systems, commissioning support, MEP coordination.', 'https://www.encoreelectric.com/careers/', '[75-Companies enrichment] Address: 7125 W Jefferson Ave, Suite 400, Lakewood, CO 80235 | Drive from 80226: 10–15 min | Employees: 501–1,000 | Category: Electrical contractor / mission critical'),
  ('Weifield Contracting', '6950 S Jordan Rd', 'Centennial', 'CO', '80112', 'Electrical contractor, MEP coordination, equipment upgrades, critical systems reliability.', 'https://www.weifieldcontracting.com/careers/', '[75-Companies enrichment] Address: 6950 S Jordan Rd, Centennial, CO 80112 | Drive from 80226: 35–45 min | Employees: 501–1,000 | Category: Electrical contractor / mission critical'),
  ('EXP', '1630 Welton St, Suite 600A', 'Denver', 'CO', '80202', 'MEP design, commissioning, operations consulting, project management.', 'https://www.exp.com/careers/', '[75-Companies enrichment] Address: 1630 Welton St, Suite 600A, Denver, CO 80202 | Drive from 80226: 20–25 min | Employees: 1,001–5,000 | Category: Engineering consultant / mission critical'),
  ('Introba', '8821 E Hampden Ave, Suite 212', 'Denver', 'CO', '80231', 'MEP, sustainability, energy, commissioning, building systems.', 'https://www.introba.com/careers', '[75-Companies enrichment] Address: 8821 E Hampden Ave, Suite 212, Denver, CO 80231 | Drive from 80226: 25–35 min | Employees: 1,000+ | Category: Building engineering consultant / sustainability'),
  ('NV5', '2650 18th St, Suite 202', 'Denver', 'CO', '80211', 'Commissioning, MEP design review, testing scripts, QA/QC, owner’s representation.', 'https://www.nv5.com/careers/', '[75-Companies enrichment] Address: 2650 18th St, Suite 202, Denver, CO 80211 | Drive from 80226: 15–25 min | Employees: 1,001–5,000 | Category: Engineering consultant / commissioning'),
  ('CAI / Commissioning Agents Inc.', 'Remote/national data-center commissioning roles; location varies by posting', NULL, NULL, NULL, 'Commissioning, test scripts, integrated systems testing, BAS, mechanical systems verification.', 'https://caiready.com/careers/', '[75-Companies enrichment] Address: Remote/national data-center commissioning roles; location varies by posting | Drive from 80226: Remote/varies min | Employees: 501–1,000 | Category: Commissioning consultant / mission critical'),
  ('Syska Hennessy Group', 'Remote/national mission-critical roles; location varies by posting', NULL, NULL, NULL, 'MEP design, cooling, critical power, commissioning, telecom/security.', 'https://syska.com/careers/', '[75-Companies enrichment] Address: Remote/national mission-critical roles; location varies by posting | Drive from 80226: Remote/varies min | Employees: 650+ | Category: Critical facilities MEP consultant'),
  ('ENERCON', 'Remote/national data-center mission-critical roles; location varies by posting', NULL, NULL, NULL, 'Mechanical/electrical design, owner''s engineering, construction support.', 'https://www.enercon.com/careers/', '[75-Companies enrichment] Address: Remote/national data-center mission-critical roles; location varies by posting | Drive from 80226: Remote/varies min | Employees: 1,001–5,000 | Category: Engineering consultant / mission critical'),
  ('Strategic Mission Critical', 'Remote/national data-center MEP roles; location varies by posting', NULL, NULL, NULL, 'Data-center MEP/fire protection design and engineering.', 'https://smc-eng.com/career/', '[75-Companies enrichment] Address: Remote/national data-center MEP roles; location varies by posting | Drive from 80226: Remote/varies min | Employees: 11–50 | Category: Data-center MEP / fire-protection engineering consultant')
) AS v(companyname, address, city, state, zip, about, careers, note)
WHERE NOT EXISTS (SELECT 1 FROM companies c WHERE c.companyname = v.companyname);
INSERT INTO companies (companyname, niche, mailing_address1, mailing_city, mailing_state, mailing_zip, company_about, careers_url, notes)
SELECT v.companyname, 'Data Center Buildout', v.address, v.city, v.state, v.zip, v.about, v.careers, v.note FROM (VALUES
  ('Spectrum Engineers', 'Remote/regional mission-critical roles; location varies by posting', NULL, NULL, NULL, 'MEP/FP, technology, commissioning and infrastructure design.', 'https://spectrum-engineers.com/careers/', '[75-Companies enrichment] Address: Remote/regional mission-critical roles; location varies by posting | Drive from 80226: Remote/varies min | Employees: 51–200 | Category: Mission-critical engineering consultant'),
  ('Turner Construction', '1401 Zuni St, Suite 301', 'Denver', 'CO', '80204', 'GC, field engineering, MEP coordination, construction management.', 'https://www.turnerconstruction.com/careers', '[75-Companies enrichment] Address: 1401 Zuni St, Suite 301, Denver, CO 80204 | Drive from 80226: 10–15 min | Employees: 10,000+ | Category: General contractor / critical facilities builder'),
  ('Howell Construction', '8085 E Harvard Ave', 'Denver', 'CO', '80231', 'GC/design-build, renovation, mission-critical upgrades, MEP coordination.', 'https://howelldenver.com/join-our-team/', '[75-Companies enrichment] Address: 8085 E Harvard Ave, Denver, CO 80231 | Drive from 80226: 25–35 min | Employees: 51–200 | Category: General contractor / design-build'),
  ('Eaton', 'Littleton, CO 80120; role location varies by posting', NULL, NULL, NULL, 'Power distribution products, application engineering, customer technical support, data-center systems.', 'https://www.eaton.com/us/en-us/company/careers.html', '[75-Companies enrichment] Address: Littleton, CO 80120; role location varies by posting | Drive from 80226: 20–30 min | Employees: ~94,000 | Category: Power management equipment supplier'),
  ('Schneider Electric', 'Denver-area sales/service roles; location varies by posting', NULL, NULL, NULL, 'Equipment, controls, power, cooling infrastructure, technical sales/application engineering.', 'https://www.se.com/us/en/about-us/careers/', '[75-Companies enrichment] Address: Denver-area sales/service roles; location varies by posting | Drive from 80226: Varies min | Employees: 150,000+ | Category: Power / cooling / automation equipment supplier'),
  ('Vertiv', 'Denver field-service and sales roles; location varies by posting', NULL, NULL, NULL, 'Thermal management, power, UPS, liquid cooling, service and commissioning.', 'https://www.vertiv.com/en-us/about/career-center/', '[75-Companies enrichment] Address: Denver field-service and sales roles; location varies by posting | Drive from 80226: Varies min | Employees: 27,000+ | Category: Power / cooling / critical infrastructure supplier'),
  ('Johnson Controls', '10289 Centennial Rd', 'Littleton', 'CO', '80127', 'HVAC controls, BAS, cooling controls, field engineering, commissioning.', 'https://jobs.johnsoncontrols.com/', '[75-Companies enrichment] Address: 10289 Centennial Rd, Littleton, CO 80127 | Drive from 80226: 15–25 min | Employees: 100,000+ | Category: HVAC / controls equipment supplier'),
  ('Trane Technologies / Trane', '445 Bryant St, Unit 5', 'Denver', 'CO', '80204', 'Cooling equipment, HVAC systems, application engineering, service and controls.', 'https://careers.tranetechnologies.com/', '[75-Companies enrichment] Address: 445 Bryant St, Unit 5, Denver, CO 80204 | Drive from 80226: 10–15 min | Employees: 40,000+ | Category: HVAC / cooling equipment supplier'),
  ('Carrier', '8100 S Akron St / 8200 S Akron St, Suite 112', 'Centennial', 'CO', '80112', 'Cooling equipment, chiller systems, thermal engineering, application support.', 'https://jobs.carrier.com/', '[75-Companies enrichment] Address: 8100 S Akron St / 8200 S Akron St, Suite 112, Centennial, CO 80112 | Drive from 80226: 35–45 min | Employees: 48,000+ | Category: HVAC / cooling equipment supplier'),
  ('Parker Hannifin', 'Denver-region/Colorado roles; location varies by posting', NULL, NULL, NULL, 'Liquid cooling components, manifolds, pumps, connectors, thermal-fluid systems.', 'https://www.parker.com/us/en/careers.html', '[75-Companies enrichment] Address: Denver-region/Colorado roles; location varies by posting | Drive from 80226: Varies min | Employees: 60,000+ | Category: Liquid cooling / thermal management supplier'),
  ('McKinstry', '16025 Table Mountain Pkwy, Suite 100', 'Golden', 'CO', '80403', 'Design-build, energy services, mechanical systems, decarbonization, construction.', 'https://www.mckinstry.com/join-us/jobs/', '[75-Companies enrichment] Address: 16025 Table Mountain Pkwy, Suite 100, Golden, CO 80403 | Drive from 80226: 25–30 min | Employees: 1,001–5,000 | Category: MEP design-build / energy services'),
  ('Southland Industries', 'Mountain West roles; location varies by posting', NULL, NULL, NULL, 'Integrated design-build MEP, HVAC, plumbing, commissioning and service.', 'https://southlandind.com/careers/job-openings', '[75-Companies enrichment] Address: Mountain West roles; location varies by posting | Drive from 80226: Varies min | Employees: 1,001–5,000 | Category: MEP design-build contractor'),
  ('EMCOR Group / EMCOR Facilities Services', 'Denver-market service/facilities roles; location varies by posting', NULL, NULL, NULL, 'Mechanical/electrical service, facilities management, HVAC, maintenance, commissioning support.', 'https://www.emcorgroup.com/careers', '[75-Companies enrichment] Address: Denver-market service/facilities roles; location varies by posting | Drive from 80226: Varies min | Employees: 38,000+ | Category: Mechanical / electrical facilities contractor')
) AS v(companyname, address, city, state, zip, about, careers, note)
WHERE NOT EXISTS (SELECT 1 FROM companies c WHERE c.companyname = v.companyname);

-- ===== 2. UPDATE 8 existing companies: switch niche to 'Data Center Buildout', preserve prior niche =====
UPDATE companies SET niche='Data Center Buildout', mailing_address1 = COALESCE(mailing_address1, '800 18th St, Suite 200'), mailing_city = COALESCE(mailing_city, 'Denver'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80202'), company_about = COALESCE(company_about, 'MEP, fire/life safety, telecom/security, commissioning and infrastructure design.'), careers_url = COALESCE(careers_url, 'https://www.hendersonengineers.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 800 18th St, Suite 200, Denver, CO 80202 | Drive from 80226: 20–25 min | Employees: 501–1,000 | Category: MEP / building systems consultant | [Prior niche: ZipRecruiter Intake]' WHERE companyname='Henderson Engineers' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET niche='Data Center Buildout', mailing_address1 = COALESCE(mailing_address1, '751 Pine Ridge Rd, Suite 360'), mailing_city = COALESCE(mailing_city, 'Golden'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80403'), company_about = COALESCE(company_about, 'Mechanical, plumbing and building systems design; strong local PE-track bridge.'), careers_url = COALESCE(careers_url, 'https://360eng.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 751 Pine Ridge Rd, Suite 360, Golden, CO 80403 | Drive from 80226: 25–30 min | Employees: 11–50 | Category: Mechanical / plumbing engineering consultant | [Prior niche: MEP / HVAC / Building Systems]' WHERE companyname='360 Engineering' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET niche='Data Center Buildout', mailing_address1 = COALESCE(mailing_address1, '255 Fillmore St, Suite 400, Denver, CO 80206; Spark Factory: 22600 E I-76 Frontage Rd, Brighton, CO'), mailing_city = COALESCE(mailing_city, NULL), mailing_state = COALESCE(mailing_state, NULL), mailing_zip = COALESCE(mailing_zip, NULL), company_about = COALESCE(company_about, 'Modular data-center manufacturing, AI infrastructure, liquid cooling, deployment engineering.'), careers_url = COALESCE(careers_url, 'https://www.crusoe.ai/about/careers'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 255 Fillmore St, Suite 400, Denver, CO 80206; Spark Factory: 22600 E I-76 Frontage Rd, Brighton, CO | Drive from 80226: 25–55 min | Employees: 501–1,000 | Category: AI infrastructure / modular data-center developer | [Prior niche: Energy / Renewables / Power]' WHERE companyname='Crusoe' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET niche='Data Center Buildout', mailing_address1 = COALESCE(mailing_address1, '717 17th St, Suite 2600, Denver, CO 80202; Denver Tech Center roles may vary'), mailing_city = COALESCE(mailing_city, NULL), mailing_state = COALESCE(mailing_state, NULL), mailing_zip = COALESCE(mailing_zip, NULL), company_about = COALESCE(company_about, 'Design engineering, owner’s engineer, commissioning, project management.'), careers_url = COALESCE(careers_url, 'https://aecom.jobs/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 717 17th St, Suite 2600, Denver, CO 80202; Denver Tech Center roles may vary | Drive from 80226: 20–35 min | Employees: 50,000+ | Category: A/E engineering consultant / data centers | [Prior niche: Construction / Civil / Heavy Industry]' WHERE companyname='AECOM' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET niche='Data Center Buildout', mailing_address1 = COALESCE(mailing_address1, 'Rocky Mountain regional office: 12121 Grant St, Suite 410, Thornton, CO 80241; HQ: 420 Sixth Ave'), mailing_city = COALESCE(mailing_city, 'Greeley'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80631'), company_about = COALESCE(company_about, 'GC, field engineering, MEP coordination, project controls.'), careers_url = COALESCE(careers_url, 'https://www.henselphelps.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: Rocky Mountain regional office: 12121 Grant St, Suite 410, Thornton, CO 80241; HQ: 420 Sixth Ave, Greeley, CO 80631 | Drive from 80226: 35–80 min | Employees: 4,000+ | Category: General contractor / advanced technology builder | [Prior niche: Construction / Civil / Heavy Industry]' WHERE companyname='Hensel Phelps' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET niche='Data Center Buildout', mailing_address1 = COALESCE(mailing_address1, '8480 E Orchard Rd, Suite 6200'), mailing_city = COALESCE(mailing_city, 'Greenwood Village'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80111'), company_about = COALESCE(company_about, 'GC, field engineering, project engineering, MEP coordination.'), careers_url = COALESCE(careers_url, 'https://www.laytonconstruction.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 8480 E Orchard Rd, Suite 6200, Greenwood Village, CO 80111 | Drive from 80226: 30–40 min | Employees: 1,001–5,000 | Category: General contractor / mission-critical builder | [Prior niche: Construction / Civil / Heavy Industry]' WHERE companyname='Layton Construction' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET niche='Data Center Buildout', mailing_address1 = COALESCE(mailing_address1, '707 17th St, Suite 2300, Denver, CO 80202; Englewood office: 9191 S Jamaica St'), mailing_city = COALESCE(mailing_city, 'Englewood'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80112'), company_about = COALESCE(company_about, 'Mechanical HVAC, controls, owner’s engineer, design/construction support for AI data centers.'), careers_url = COALESCE(careers_url, 'https://www.jacobs.com/careers-jacobs'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 707 17th St, Suite 2300, Denver, CO 80202; Englewood office: 9191 S Jamaica St, Englewood, CO 80112 | Drive from 80226: 20–40 min | Employees: 45,000+ | Category: A/E engineering consultant / AI data centers | [Prior niche: Construction / Civil / Heavy Industry]' WHERE companyname='Jacobs' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET niche='Data Center Buildout', mailing_address1 = COALESCE(mailing_address1, '410 17th St, Suite 1400'), mailing_city = COALESCE(mailing_city, 'Denver'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80202'), company_about = COALESCE(company_about, 'MEP design, campus infrastructure, high-availability mechanical systems, construction support.'), careers_url = COALESCE(careers_url, 'https://www.stantec.com/en/careers'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 410 17th St, Suite 1400, Denver, CO 80202 | Drive from 80226: 20–25 min | Employees: 32,000+ | Category: A/E engineering consultant / mission critical | [Prior niche: Construction / Civil / Heavy Industry]' WHERE companyname='Stantec' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');

-- ===== 3. UPDATE 26 existing 'Data Center Buildout' companies: enrich with address / about =====
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '896 Tabor St'), mailing_city = COALESCE(mailing_city, 'Lakewood'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80401'), company_about = COALESCE(company_about, 'MEP design, commissioning, technology systems, existing-facility expansions.'), careers_url = COALESCE(careers_url, 'https://catorruma.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 896 Tabor St, Lakewood, CO 80401 | Drive from 80226: 10–15 min | Employees: 115+ | Category: MEP engineering consultant / commissioning' WHERE companyname='Cator Ruma & Associates' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '12600 W Colfax Ave, Suite A400'), mailing_city = COALESCE(mailing_city, 'Lakewood'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80215'), company_about = COALESCE(company_about, 'Mechanical/electrical engineering from concept through design, construction, closeout; data-center cooling and power design.'), careers_url = COALESCE(careers_url, 'https://www.rmhgroup.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 12600 W Colfax Ave, Suite A400, Lakewood, CO 80215 | Drive from 80226: 10–15 min | Employees: 51–200 | Category: MEP engineering consultant' WHERE companyname='The RMH Group' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '14143 Denver West Pkwy, Suite 550'), mailing_city = COALESCE(mailing_city, 'Golden'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80401'), company_about = COALESCE(company_about, 'Mechanical, electrical, plumbing, fire/life-safety, technology systems; potential data-center upgrades and institutional data centers.'), careers_url = COALESCE(careers_url, 'https://bcer.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 14143 Denver West Pkwy, Suite 550, Golden, CO 80401 | Drive from 80226: 15–20 min | Employees: 51–200 | Category: MEP engineering consultant / technology / life-safety' WHERE companyname='BCER Engineering' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '1120 N Lincoln St, Suite 1200'), mailing_city = COALESCE(mailing_city, 'Denver'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80203'), company_about = COALESCE(company_about, 'MEP design, CFD, IT/controls, sustainable infrastructure for data centers.'), careers_url = COALESCE(careers_url, 'https://swansonrink.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 1120 N Lincoln St, Suite 1200, Denver, CO 80203 | Drive from 80226: 20–25 min | Employees: 51–200 | Category: MEP engineering consultant / data-center specialist' WHERE companyname='Swanson Rink' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '7600 E Orchard Rd, Suite 250-S, Greenwood Village, CO 80111; Denver office: 1400 Glenarm Pl, Suite 101'), mailing_city = COALESCE(mailing_city, 'Denver'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80202'), company_about = COALESCE(company_about, 'MEP design, HVAC, plumbing, fire protection, technology, commissioning support.'), careers_url = COALESCE(careers_url, 'https://www.imegcorp.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 7600 E Orchard Rd, Suite 250-S, Greenwood Village, CO 80111; Denver office: 1400 Glenarm Pl, Suite 101, Denver, CO 80202 | Drive from 80226: 25–35 min | Employees: 1,000–5,000 | Category: MEP / data-center engineering consultant' WHERE companyname='IMEG' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '1525 N Raleigh St, Suite 400, Denver, CO 80204; field office: 5180 E Smith Rd, Unit F'), mailing_city = COALESCE(mailing_city, 'Denver'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80216'), company_about = COALESCE(company_about, 'Data-center civil/site, mechanical, electrical and interdisciplinary design for large technology clients.'), careers_url = COALESCE(careers_url, 'https://www.olsson.com/current-openings'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 1525 N Raleigh St, Suite 400, Denver, CO 80204; field office: 5180 E Smith Rd, Unit F, Denver, CO 80216 | Drive from 80226: 10–20 min | Employees: 1,001–5,000 | Category: Engineering consultant / data-center site and infrastructure' WHERE companyname='Olsson' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '1670 Broadway, Suite 3400'), mailing_city = COALESCE(mailing_city, 'Denver'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80202'), company_about = COALESCE(company_about, 'Design engineering, mission-critical project management, MEP coordination, construction-phase services.'), careers_url = COALESCE(careers_url, 'https://www.hdrinc.com/careers'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 1670 Broadway, Suite 3400, Denver, CO 80202 | Drive from 80226: 20–25 min | Employees: 13,000+ | Category: A/E engineering consultant / mission critical' WHERE companyname='HDR' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '9191 S Jamaica St'), mailing_city = COALESCE(mailing_city, 'Englewood'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80112'), company_about = COALESCE(company_about, 'Integrated engineering, preconstruction, design-build, commissioning, project controls.'), careers_url = COALESCE(careers_url, 'https://www.burnsmcd.com/careers'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 9191 S Jamaica St, Englewood, CO 80112 | Drive from 80226: 30–40 min | Employees: 14,500+ | Category: EPC / engineering / construction' WHERE companyname='Burns & McDonnell' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '999 18th St, Denver, CO 80202; 2000 S Colorado Blvd'), mailing_city = COALESCE(mailing_city, 'Denver'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80222'), company_about = COALESCE(company_about, 'Mechanical cooling/HVAC design, electrical, fire protection, telecom and commissioning for data centers.'), careers_url = COALESCE(careers_url, 'https://www.wsp.com/en-us/careers'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 999 18th St, Denver, CO 80202; 2000 S Colorado Blvd, Denver, CO 80222 | Drive from 80226: 20–30 min | Employees: 83,000 worldwide | Category: Data-center MEP engineering consultant' WHERE companyname='WSP / kW Mission Critical Engineering' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '9250 E Costilla Ave, Suite 220, Greenwood Village, CO 80112; 165 S Union Blvd, Suite 360'), mailing_city = COALESCE(mailing_city, 'Lakewood'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80228'), company_about = COALESCE(company_about, 'MEP design, commissioning, field observation, telecom/data-center infrastructure.'), careers_url = COALESCE(careers_url, 'https://salasobrien.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 9250 E Costilla Ave, Suite 220, Greenwood Village, CO 80112; 165 S Union Blvd, Suite 360, Lakewood, CO 80228 | Drive from 80226: 10–35 min | Employees: 1,000–5,000 | Category: MEP engineering consultant / commissioning' WHERE companyname='Salas O’Brien' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '5613 DTC Pkwy, Suite 450'), mailing_city = COALESCE(mailing_city, 'Greenwood Village'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80111'), company_about = COALESCE(company_about, 'GC, design coordination, MEP coordination, commissioning interface, construction delivery.'), careers_url = COALESCE(careers_url, 'https://www.dpr.com/company/careers/current-positions'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 5613 DTC Pkwy, Suite 450, Greenwood Village, CO 80111 | Drive from 80226: 30–40 min | Employees: 10,000+ | Category: General contractor / mission-critical builder' WHERE companyname='DPR Construction' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '2000 S Colorado Blvd, Suite 2-500'), mailing_city = COALESCE(mailing_city, 'Denver'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80222'), company_about = COALESCE(company_about, 'GC, MEP coordination, preconstruction, scheduling, subcontractor coordination, field engineering.'), careers_url = COALESCE(careers_url, 'https://www.pcl.com/careers'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 2000 S Colorado Blvd, Suite 2-500, Denver, CO 80222 | Drive from 80226: 25–35 min | Employees: 5,000+ | Category: General contractor / data-center builder' WHERE companyname='PCL Construction' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '6363 S Fiddlers Green Cir, Suite 1300'), mailing_city = COALESCE(mailing_city, 'Greenwood Village'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80111'), company_about = COALESCE(company_about, 'GC, MEP preconstruction, trade coordination, scheduling, commissioning readiness.'), careers_url = COALESCE(careers_url, 'https://www.holderconstruction.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 6363 S Fiddlers Green Cir, Suite 1300, Greenwood Village, CO 80111 | Drive from 80226: 30–40 min | Employees: 1,001–5,000 | Category: General contractor / data-center builder' WHERE companyname='Holder Construction' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '3301 Lewiston St'), mailing_city = COALESCE(mailing_city, 'Aurora'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80011'), company_about = COALESCE(company_about, 'Mechanical construction, prefabrication, modular data centers, HVAC/plumbing/process piping, power modules, skids.'), careers_url = COALESCE(careers_url, 'https://rkindustries.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 3301 Lewiston St, Aurora, CO 80011 | Drive from 80226: 35–45 min | Employees: 1,000+ | Category: Mechanical contractor / modular fabrication / mission critical' WHERE companyname='RK Industries / RK Mechanical / RK Mission Critical' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '1100 W 120th Ave, Suite 900'), mailing_city = COALESCE(mailing_city, 'Westminster'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80234'), company_about = COALESCE(company_about, 'Mechanical construction, fabrication, HVAC, piping, service, commissioning support.'), careers_url = COALESCE(careers_url, 'https://www.usengineering.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 1100 W 120th Ave, Suite 900, Westminster, CO 80234 | Drive from 80226: 25–35 min | Employees: 1,000–5,000 | Category: Mechanical contractor / prefabrication' WHERE companyname='U.S. Engineering' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '12300 Pecos St'), mailing_city = COALESCE(mailing_city, 'Westminster'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80234'), company_about = COALESCE(company_about, 'HVAC, plumbing, controls, service, design-build mechanical construction.'), careers_url = COALESCE(careers_url, 'https://mtechg.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 12300 Pecos St, Westminster, CO 80234 | Drive from 80226: 25–35 min | Employees: 501–1,000 | Category: Mechanical contractor / design-build' WHERE companyname='MTech Mechanical' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '12789 Emerson St'), mailing_city = COALESCE(mailing_city, 'Thornton'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80241'), company_about = COALESCE(company_about, 'Mechanical construction, fabrication, HVAC/piping/plumbing, ongoing service and maintenance.'), careers_url = COALESCE(careers_url, 'https://www.murphynet.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 12789 Emerson St, Thornton, CO 80241 | Drive from 80226: 35–45 min | Employees: 501–1,000 | Category: Mechanical contractor / service / construction' WHERE companyname='Murphy Company' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '5001 S Zuni St'), mailing_city = COALESCE(mailing_city, 'Littleton'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80120'), company_about = COALESCE(company_about, 'BAS controls, HVAC service, controls integration, energy analytics.'), careers_url = COALESCE(careers_url, 'https://www.long.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 5001 S Zuni St, Littleton, CO 80120 | Drive from 80226: 15–25 min | Employees: 501–1,000 | Category: Building automation / HVAC controls' WHERE companyname='LONG Building Technologies' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '5700 S Quebec St, Suite 210'), mailing_city = COALESCE(mailing_city, 'Greenwood Village'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80111'), company_about = COALESCE(company_about, 'HVAC design-build, controls, service, mechanical construction.'), careers_url = COALESCE(careers_url, 'https://www.haynesmech.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 5700 S Quebec St, Suite 210, Greenwood Village, CO 80111 | Drive from 80226: 30–40 min | Employees: 201–500 | Category: Mechanical contractor / design-build HVAC' WHERE companyname='Haynes Mechanical Systems' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '6750 W 52nd Ave, Suite H'), mailing_city = COALESCE(mailing_city, 'Arvada'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80002'), company_about = COALESCE(company_about, 'BAS engineering, controls, commissioning, energy optimization for critical facilities.'), careers_url = COALESCE(careers_url, 'https://albireoenergy.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 6750 W 52nd Ave, Suite H, Arvada, CO 80002 | Drive from 80226: 15–25 min | Employees: 501–1,000 | Category: Building automation / controls / energy services' WHERE companyname='Albireo Energy' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '5837 S Gallup St'), mailing_city = COALESCE(mailing_city, 'Littleton'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80120'), company_about = COALESCE(company_about, 'Retrofit engineering, construction, BAS/HVAC controls, energy studies, reliability upgrades.'), careers_url = COALESCE(careers_url, 'https://enabledenergy.net/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 5837 S Gallup St, Littleton, CO 80120 | Drive from 80226: 15–25 min | Employees: 51–200 | Category: Data-center retrofit / energy engineering / construction' WHERE companyname='Enabled Energy' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '3200 Cherry Creek S Dr, Suite 500'), mailing_city = COALESCE(mailing_city, 'Denver'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80209'), company_about = COALESCE(company_about, 'Developer-side site, design, procurement and delivery of large-scale data centers.'), careers_url = COALESCE(careers_url, 'https://fleetdatacenters.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 3200 Cherry Creek S Dr, Suite 500, Denver, CO 80209 | Drive from 80226: 25–35 min | Employees: 11–50 | Category: Data-center developer / build-to-suit' WHERE companyname='Fleet Data Centers' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '200 Clayton St, Suite 450'), mailing_city = COALESCE(mailing_city, 'Denver'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80206'), company_about = COALESCE(company_about, 'Owner/operator development, operations, MEP design standards, facility engineering.'), careers_url = COALESCE(careers_url, 'https://vantage-dc.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 200 Clayton St, Suite 450, Denver, CO 80206 | Drive from 80226: 25–30 min | Employees: 1,001–5,000 | Category: Data-center owner / operator / developer' WHERE companyname='Vantage Data Centers' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, 'Parker facility: 15255 Compark Blvd, Parker, CO 80134; other Denver metro sites vary'), mailing_city = COALESCE(mailing_city, NULL), mailing_state = COALESCE(mailing_state, NULL), mailing_zip = COALESCE(mailing_zip, NULL), company_about = COALESCE(company_about, 'Owner/operator development, facility operations, liquid cooling readiness, colocation infrastructure.'), careers_url = COALESCE(careers_url, 'https://www.flexential.com/careers'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: Parker facility: 15255 Compark Blvd, Parker, CO 80134; other Denver metro sites vary | Drive from 80226: 30–60 min | Employees: 1,001–5,000 | Category: Data-center owner / operator / colocation' WHERE companyname='Flexential' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '15013 Denver West Pkwy'), mailing_city = COALESCE(mailing_city, 'Golden'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80401'), company_about = COALESCE(company_about, 'Data-center cooling research, controls, thermal management, liquid cooling, experiments.'), careers_url = COALESCE(careers_url, 'https://www.nrel.gov/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 15013 Denver West Pkwy, Golden, CO 80401 | Drive from 80226: 15–20 min | Employees: 3,000+ | Category: Research lab / data-center energy systems' WHERE companyname='NREL / National Renewable Energy Laboratory' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
UPDATE companies SET mailing_address1 = COALESCE(mailing_address1, '12600 W Colfax Ave, Suite C-500'), mailing_city = COALESCE(mailing_city, 'Lakewood'), mailing_state = COALESCE(mailing_state, 'CO'), mailing_zip = COALESCE(mailing_zip, '80215'), company_about = COALESCE(company_about, 'Power infrastructure design, system studies, substations, utility interconnection.'), careers_url = COALESCE(careers_url, 'https://neiengineering.com/careers/'), notes = COALESCE(notes,'') || E'\n' || '[75-Companies enrichment] Address: 12600 W Colfax Ave, Suite C-500, Lakewood, CO 80215 | Drive from 80226: 10–15 min | Employees: 51–200 | Category: Power engineering consultant' WHERE companyname='NEI Electric Power Engineering' AND (notes IS NULL OR notes NOT LIKE '%75-Companies enrichment%');
